aienuo-boot:
  version: 1.0.0
server:
  tomcat:
    max-swallow-size: -1
  servlet:
    context-path: /
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
spring:
  application:
    name: agile
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
      file-size-threshold: 100MB
  profiles:
    active: dev
  messages:
    basename: i18n/response
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    # Druid的其他属性配置
    druid:
      # 初始化时建立物理连接的个数
      initial-size: 5
      # 连接池的最小空闲数量
      min-idle: 5
      # 连接池最大连接数量
      max-active: 20
      # 获取连接时最大等待时间，单位毫秒
      max-wait: 60000
      # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
      # 既作为检测的间隔时间又作为testWhileIdel执行的依据
      time-between-eviction-runs-millis: 60000
      # 销毁线程时检测当前连接的最后活动时间和当前时间差大于该值时，关闭当前连接(配置连接在池中的最小生存时间)
      min-evictable-idle-time-millis: 30000
      # 用来检测数据库连接是否有效的sql 必须是一个查询语句(oracle中为 select 1 from dual)
      validation-query: SELECT 1 FROM DUAL
      # 申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-borrow: false
      # 归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-return: false
      # 是否缓存 preparedStatement, 也就是PSCache,PSCache对支持游标的数据库性能提升巨大，比如说oracle,在mysql下建议关闭。
      pool-prepared-statements: false
      # 置监控统计拦截的filters，去掉后监控界面sql无法统计，stat: 监控统计、Slf4j:日志记录、waLL: 防御sqL注入
      filters: stat,wall,slf4j
      # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
      max-pool-prepared-statement-per-connection-size: -1
      # 合并多个 DruidDataSource 的监控数据
      use-global-data-source-stat: true
      # 通过 connectProperties 属性来打开mergeSql功能；慢SQL记录
      connect-properties: druid.stat.mergeSql=\true;druid.stat.slowSqlMillis\=5000
      #
      web-stat-filter:
        # 是否启用StatFilter默认值true
        enabled: true
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤的格式
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.png,*.css,*.ico
      #
      stat-view-servlet:
        # 是否启用StatViewServlet默认值true
        enabled: true
        # 访问路径为/druid时，跳转到StatViewServlet
        url-pattern: /druid/*
        # 是否能够重置数据
        reset-enable: false
        # 需要账号密码才能访问控制台，默认为 root
        login-username: admin
        login-password: admin
        # IP白名单
        allow: 127.0.0.1,192.168.137.1,192.168.1.114,192.168.1.1,192.168.211.1
        # IP黑名单（共同存在时，deny优先于allow）
        deny:
    dynamic:
      primary: master
      strict: false
  aop:
    proxy-target-class: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    static-path-pattern: /**
    format:
      date: yyyy-MM-dd
  autoconfigure:
  # exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
  web:
    resources:
      static-locations: classpath:/templates/
mybatis-plus:
  mapper-locations: classpath:com/aienuo/agile/module/**/mapper/xml/*Mapper.xml
  checkConfigLocation: true
  global-config:
    banner: false
    db-config:
      id-type: ASSIGN_ID
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: 'null'
# springdoc-openapi 项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  # OpenAPI文档相关参数
  api-docs:
    # OpenAPI文档开关, true: 开启OpenAPI文档访问功能, false: 关闭。
    enabled: true
    # JSON格式的OpenAPI文档的访问路径
    path: /v3/api-docs
  # 分组配置
  group-configs:
    - group: '对外提供接口'
      paths-to-match: '/**'
      packages-to-scan: com.aienuo.agile.module.api.controller
    - group: '后台管理接口'
      paths-to-match: '/**'
      packages-to-scan: com.aienuo.agile.module.system.controller
logging:
  config: classpath:config/logbackConfig/logback-${spring.profiles.active}.xml
